# Generated by Django 4.0.6 on 2022-07-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='desciption',
            new_name='description',
        ),
    ]
