# Generated by Django 4.0.6 on 2022-07-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_rename_desciption_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='figure',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
